<?php

namespace Proxies\__CG__\OnlineTest\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Exam extends \OnlineTest\AdminBundle\Entity\Exam implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'id', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'examId', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'examName', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'examCodename', 'students', 'papers', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'isRealName', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'isOrder', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'isOnTime', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'isOverAndSave', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'starttime', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'endtime', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'questions', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'kinds');
        }

        return array('__isInitialized__', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'id', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'examId', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'examName', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'examCodename', 'students', 'papers', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'isRealName', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'isOrder', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'isOnTime', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'isOverAndSave', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'starttime', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'endtime', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'questions', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Exam' . "\0" . 'kinds');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Exam $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamId($examId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamId', array($examId));

        return parent::setExamId($examId);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamId', array());

        return parent::getExamId();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamName($examName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamName', array($examName));

        return parent::setExamName($examName);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamName', array());

        return parent::getExamName();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamCodename($examCodename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamCodename', array($examCodename));

        return parent::setExamCodename($examCodename);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamCodename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamCodename', array());

        return parent::getExamCodename();
    }

    /**
     * {@inheritDoc}
     */
    public function addStudent(\OnlineTest\AdminBundle\Entity\Student $students)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStudent', array($students));

        return parent::addStudent($students);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStudent(\OnlineTest\AdminBundle\Entity\Student $students)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStudent', array($students));

        return parent::removeStudent($students);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudents', array());

        return parent::getStudents();
    }

    /**
     * {@inheritDoc}
     */
    public function addPaper(\OnlineTest\AdminBundle\Entity\Paper $papers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPaper', array($papers));

        return parent::addPaper($papers);
    }

    /**
     * {@inheritDoc}
     */
    public function removePaper(\OnlineTest\AdminBundle\Entity\Paper $papers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePaper', array($papers));

        return parent::removePaper($papers);
    }

    /**
     * {@inheritDoc}
     */
    public function getPapers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPapers', array());

        return parent::getPapers();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRealName($isRealName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRealName', array($isRealName));

        return parent::setIsRealName($isRealName);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRealName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRealName', array());

        return parent::getIsRealName();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOrder($isOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOrder', array($isOrder));

        return parent::setIsOrder($isOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOrder', array());

        return parent::getIsOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOnTime($isOnTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOnTime', array($isOnTime));

        return parent::setIsOnTime($isOnTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOnTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOnTime', array());

        return parent::getIsOnTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOverAndSave($isOverAndSave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOverAndSave', array($isOverAndSave));

        return parent::setIsOverAndSave($isOverAndSave);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOverAndSave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOverAndSave', array());

        return parent::getIsOverAndSave();
    }

    /**
     * {@inheritDoc}
     */
    public function setStarttime($starttime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStarttime', array($starttime));

        return parent::setStarttime($starttime);
    }

    /**
     * {@inheritDoc}
     */
    public function getStarttime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStarttime', array());

        return parent::getStarttime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndtime($endtime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndtime', array($endtime));

        return parent::setEndtime($endtime);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndtime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndtime', array());

        return parent::getEndtime();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestions($questions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestions', array($questions));

        return parent::setQuestions($questions);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestions', array());

        return parent::getQuestions();
    }

    /**
     * {@inheritDoc}
     */
    public function setKinds($kinds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKinds', array($kinds));

        return parent::setKinds($kinds);
    }

    /**
     * {@inheritDoc}
     */
    public function getKinds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKinds', array());

        return parent::getKinds();
    }

}
