security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        OnlineTest\AdminBundle\Entity\Student: 
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        role_hierarchy:
            ROLE_STUDENT:     ROLE_STUDENT
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                provider: [students, fos_userbundle, in_memory]
        students:
            entity:
                class: OnlineTest\AdminBundle\Entity\Student  
                property: username
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2a$12$w/aHvnC/XNeDVrrl65b3dept8QcKqpADxUlbraVXXsC03Jam5hvoO
                        roles: 'ROLE_USER'
                    ryan:
                        password: $2a$12$HmOsqRDJK0HuMDQ5Fb2.AOLMQHyNHGD0seyjU3lEVusjT72QQEIpW
                        roles: 'ROLE_USER'
                    admin:
                        password: $2a$12$HmOsqRDJK0HuMDQ5Fb2.AOLMQHyNHGD0seyjU3lEVusjT72QQEIpW
                        roles: 'ROLE_ADMIN'

    firewalls:
        student:
            pattern: ^/student
            anonymous: ~
            form_login: 
                provider: students
                login_path: student_login
                check_path: student_login_check
                csrf_provider: form.csrf_provider
                always_use_default_target_path: false
                default_target_path: exam_prepare
            logout:
                path: /student/logout
                target: /student/login

        
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: false
                default_target_path: admin_homepage
            logout:  
                path: /logout
                target: /login
            anonymous:    true
            remember_me:
                key: "%secret%"
                lifetime: 1209600
                path: /
                domain: ~
            
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/student/login/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/student/exam/isRealname$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/student/exam/paper_status$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/student/exam/prepare/unrealname, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/student/exam/unrealname, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/student/exam/submit_paper, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/student/exam, role: ROLE_STUDENT }
        