<?php

namespace OnlineTest\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExamRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRecordRepository extends EntityRepository {

    //删除单个记录
    public function deleteOneRecord($recordId) {
        $record = $this->find($recordId);
        $this->getEntityManager()->remove($record);
        $this->getEntityManager()->flush();
    }

    //删除选中的试卷
    public function deleteSelectedRecords($selectedRecords) {
        foreach ($selectedRecords as $selectedRecord) {
            $this->deleteOneRecord($selectedRecord);
        }
        return 1;
    }

    //通过考试编号和学生编号查找考试记录
    public function findOneByPIdAndSId($paperId, $studentId) {
        $query = $this->getEntityManager()
                        ->createQuery(
                                'SELECT er FROM OnlineTestMainBundle:ExamRecord er '
                                . 'join er.paper p '
                                . 'join er.student s '
                                . 'where p.id= :pid and s.id= :sid'
                        )->setParameter('pid', $paperId)
                        ->setParameter('sid', $studentId);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
        
    }

}
