<?php

namespace Proxies\__CG__\OnlineTest\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Question extends \OnlineTest\AdminBundle\Entity\Question implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'id', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'questionContent', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'answer', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'type', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'questionImages', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'optionRate', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'kind', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'isMustSelect', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'isOptionShuffle');
        }

        return array('__isInitialized__', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'id', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'questionContent', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'answer', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'type', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'questionImages', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'optionRate', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'kind', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'isMustSelect', '' . "\0" . 'OnlineTest\\AdminBundle\\Entity\\Question' . "\0" . 'isOptionShuffle');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Question $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestionContent($questionContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestionContent', array($questionContent));

        return parent::setQuestionContent($questionContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestionContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestionContent', array());

        return parent::getQuestionContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer($answer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer', array($answer));

        return parent::setAnswer($answer);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer', array());

        return parent::getAnswer();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestionImages($questionImages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestionImages', array($questionImages));

        return parent::setQuestionImages($questionImages);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestionImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestionImages', array());

        return parent::getQuestionImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptionRate($optionRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptionRate', array($optionRate));

        return parent::setOptionRate($optionRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionRate', array());

        return parent::getOptionRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setKind($kind)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKind', array($kind));

        return parent::setKind($kind);
    }

    /**
     * {@inheritDoc}
     */
    public function getKind()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKind', array());

        return parent::getKind();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMustSelect($isMustSelect)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMustSelect', array($isMustSelect));

        return parent::setIsMustSelect($isMustSelect);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsMustSelect()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsMustSelect', array());

        return parent::getIsMustSelect();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOptionShuffle($isOptionShuffle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOptionShuffle', array($isOptionShuffle));

        return parent::setIsOptionShuffle($isOptionShuffle);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOptionShuffle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOptionShuffle', array());

        return parent::getIsOptionShuffle();
    }

}
