<?php

namespace Proxies\__CG__\OnlineTest\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ExamRecord extends \OnlineTest\MainBundle\Entity\ExamRecord implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'id', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'username', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'paperId', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'answer', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'score', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'paper', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'student', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'answers');
        }

        return array('__isInitialized__', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'id', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'username', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'paperId', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'answer', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'score', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'paper', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'student', '' . "\0" . 'OnlineTest\\MainBundle\\Entity\\ExamRecord' . "\0" . 'answers');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ExamRecord $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaperId($paperId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaperId', array($paperId));

        return parent::setPaperId($paperId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaperId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaperId', array());

        return parent::getPaperId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer($answer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer', array($answer));

        return parent::setAnswer($answer);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer', array());

        return parent::getAnswer();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore($score)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore', array($score));

        return parent::setScore($score);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore', array());

        return parent::getScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaper(\OnlineTest\AdminBundle\Entity\Paper $paper = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaper', array($paper));

        return parent::setPaper($paper);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaper()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaper', array());

        return parent::getPaper();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudent(\OnlineTest\AdminBundle\Entity\Student $student = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudent', array($student));

        return parent::setStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudent', array());

        return parent::getStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswers($answers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswers', array($answers));

        return parent::setAnswers($answers);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswers', array());

        return parent::getAnswers();
    }

}
