OnlineTest\AdminBundle\Entity\Admin:
    type: entity
    table: null
    repositoryClass: OnlineTest\AdminBundle\Entity\AdminRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
