<?php

namespace OnlineTest\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends EntityRepository
{
    public function findInactiveAdmin(){
        return $this->getEntityManager()
                ->createQuery('select a from OnlineTestAdminBundle:Admin a where a.enabled=0')->getResult();
    }
    //激活单个教师
    public function activeOneTeacher($username){
        $admin=$this->findOneByUsername($username);
        $admin->setEnabled(true);
        $this->getEntityManager()->flush();
    }
    //删除单个教师
    public function deleteOneTeacher($username){
        $admin=$this->findOneByUsername($username);
        $this->getEntityManager()->remove($admin);
        $this->getEntityManager()->flush();
    }
    //删除选中的教师
    public function deleteSelectedTeacher($selectedTeachers){
        foreach ($selectedTeachers as $selectedTeacher) {
            $this->deleteOneTeacher($selectedTeacher);
        }
        return 1;
    }
    //激活选中到教师
    public function activeSelectedTeacher($selectedTeachers){
        foreach ($selectedTeachers as $selectedTeacher) {
            $this->activeOneTeacher($selectedTeacher);
        }
        return 1;
    }
    //失效单个教师
    public function deactiveOneTeacher($username){
        $admin=$this->findOneByUsername($username);
        $admin->setEnabled(false);
        $this->getEntityManager()->flush();
    }
    //失效选中到教师
    public function deactiveSelectedTeacher($selectedTeachers){
        foreach ($selectedTeachers as $selectedTeacher) {
            $this->deactiveOneTeacher($selectedTeacher);
        }
        return 1;
    }
}
