<?php

namespace OnlineTest\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends EntityRepository
{
    //删除单个考试
    public function endOneExam($examId){
        $exam=$this->find($examId);
        $exam->setIsOverAndSave(1);
        $this->getEntityManager()->flush();
    }
    //删除选中的试卷
    public function endSelectedExams($selectedExams){
        foreach ($selectedExams as $selectedExam) {
            $this->endOneExam($selectedExam);
        }
        return 1;
    }
    //重新启用单个考试
    public function restartOneExam($examId){
        $exam=$this->find($examId);
        $exam->setIsOverAndSave(0);
        $this->getEntityManager()->flush();
    }
    //重新启用选中的试卷
    public function restartSelectedExams($selectedExams){
        foreach ($selectedExams as $selectedExam) {
            $this->restartOneExam($selectedExam);
        }
        return 1;
    }
}
