<?php

namespace OnlineTest\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaperRepository extends EntityRepository
{
    //删除单个试卷
    public function deleteOnePaper($paperId){
        $paper=$this->findOneById($paperId);
        $this->getEntityManager()->remove($paper);
        $this->getEntityManager()->flush();
        return 1;
    }
    //删除选中的试卷
    public function deleteSelectedPapers($selectedPapers){
        foreach ($selectedPapers as $selectedPaper) {
            $this->deleteOnePaper($selectedPaper);
        }
        return 1;
    }
    //查找准备考试和开始入场的试卷
    public function findPapers(){
        return $this->getEntityManager()
                ->createQuery('select p from OnlineTestAdminBundle:Paper p where (p.status=1 or p.status=2)')->getResult();
    }
}
